### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by hgk8769789** [HypedDomi/Vencord-Plugins#4]
import-plugins:~plugins:128:17: ERROR: Could not resolve "./userplugins/Keyboard-Sounds"
 ELIFECYCLE  Command failed with exit code 1.

**Comment by HypedDomi** [comment]
Don’t clone the Repo. You need the place the file into the userplugins folder

**Comment by hgk8769789** [comment]
Sorry I meant to send this: X [ERROR] Could not resolve "./userplugins/sounds"

    import-plugins:~plugins:130:17:
      130 │ import p129 from "./userplugins/sounds";
          ╵                  ~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "./userplugins/sounds"

    import-plugins:~plugins:130:17:
      130 │ import p129 from "./userplugins/sounds";
          ╵                  ~~~~~~~~~~~~~~~~~~~~~~

1 error
Build failed
Build failed with 1 error:
import-plugins:~plugins:130:17: ERROR: Could not resolve "./userplugins/sounds"
1 error
 ELIFECYCLE  Command failed with exit code 1.

C:\Users\USER\Vencord\src\userplugins>

**Comment by hgk8769789** [comment]
oh ok tnx,
